/**
 * Multi-theme design tokens with custom background gradients.
 */

export const fontSizes = {
  xs: 10,
  sm: 12,
  md: 14,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

export const borderRadius = {
  sm: 6,
  md: 12,
  lg: 20,
  full: 999,
};

export const shadows = {
  sm: { shadowColor: '#000000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 2 },
  md: { shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 4 },
  lg: { shadowColor: '#000000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 8, elevation: 8 },
};

const sharedTokens = { fontSizes, spacing, borderRadius, shadows };

export const themes = {
  forest: {
    id: 'forest',
    name: 'Forest Slate',
    isDark: false,
    colors: {
      primary: '#1B4D6A',
      accent: '#F5A623',
      background: '#F8F9FA',
      surface: '#FFFFFF',
      border: '#E5E7EB',
      error: '#E53935',
      success: '#43A047',
      textPrimary: '#1A1A2E',
      textSecondary: '#6B7280',
      textTertiary: '#9CA3AF',
    },
    backgroundGradient: ['#1B4D6A14', '#F8F9FA'],
    ...sharedTokens,
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean Blue',
    isDark: false,
    colors: {
      primary: '#0277BD',
      accent: '#FFB300',
      background: '#F0F7FF',
      surface: '#FFFFFF',
      border: '#E5E7EB',
      error: '#E53935',
      success: '#43A047',
      textPrimary: '#0F172A',
      textSecondary: '#64748B',
      textTertiary: '#94A3B8',
    },
    backgroundGradient: ['#0277BD14', '#F0F7FF'],
    ...sharedTokens,
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight Purple',
    isDark: false,
    colors: {
      primary: '#7C4DFF',
      accent: '#00E676',
      background: '#F3F0FF',
      surface: '#FFFFFF',
      border: '#E5E7EB',
      error: '#E53935',
      success: '#43A047',
      textPrimary: '#1E1B4B',
      textSecondary: '#6B7280',
      textTertiary: '#9CA3AF',
    },
    backgroundGradient: ['#7C4DFF14', '#F3F0FF'],
    ...sharedTokens,
  },
  sakura: {
    id: 'sakura',
    name: 'Sakura Pink',
    isDark: false,
    colors: {
      primary: '#E91E8C',
      accent: '#9C27B0',
      background: '#FFF0F6',
      surface: '#FFFFFF',
      border: '#E5E7EB',
      error: '#E53935',
      success: '#43A047',
      textPrimary: '#2D1525',
      textSecondary: '#705D68',
      textTertiary: '#A897A1',
    },
    backgroundGradient: ['#E91E8C14', '#FFF0F6'],
    ...sharedTokens,
  },
  ember: {
    id: 'ember',
    name: 'Ember Orange',
    isDark: false,
    colors: {
      primary: '#E64A19',
      accent: '#FFB300',
      background: '#FFF8F5',
      surface: '#FFFFFF',
      border: '#E5E7EB',
      error: '#E53935',
      success: '#43A047',
      textPrimary: '#29140E',
      textSecondary: '#6E5C57',
      textTertiary: '#A3918C',
    },
    backgroundGradient: ['#E64A1914', '#FFF8F5'],
    ...sharedTokens,
  },
  forestDark: {
    id: 'forestDark',
    name: 'Forest Dark',
    isDark: true,
    colors: {
      primary: '#4D8BAE',
      accent: '#F5A623',
      background: '#1A1A2A',
      surface: '#252535',
      border: '#353545',
      error: '#EF5350',
      success: '#66BB6A',
      textPrimary: '#F0F0F5',
      textSecondary: '#A0A0B5',
      textTertiary: '#707085',
    },
    backgroundGradient: ['#4D8BAE1F', '#1A1A2A'],
    ...sharedTokens,
  },
  oceanDark: {
    id: 'oceanDark',
    name: 'Ocean Dark',
    isDark: true,
    colors: {
      primary: '#29B6F6',
      accent: '#FFD54F',
      background: '#1A1A2A',
      surface: '#252535',
      border: '#353545',
      error: '#EF5350',
      success: '#66BB6A',
      textPrimary: '#F0F0F5',
      textSecondary: '#A0A0B5',
      textTertiary: '#707085',
    },
    backgroundGradient: ['#29B6F61F', '#1A1A2A'],
    ...sharedTokens,
  },
  midnightDark: {
    id: 'midnightDark',
    name: 'Midnight Dark',
    isDark: true,
    colors: {
      primary: '#B388FF',
      accent: '#69F0AE',
      background: '#1A1A2A',
      surface: '#252535',
      border: '#353545',
      error: '#EF5350',
      success: '#66BB6A',
      textPrimary: '#F0F0F5',
      textSecondary: '#A0A0B5',
      textTertiary: '#707085',
    },
    backgroundGradient: ['#B388FF1F', '#1A1A2A'],
    ...sharedTokens,
  },
  sakuraDark: {
    id: 'sakuraDark',
    name: 'Sakura Dark',
    isDark: true,
    colors: {
      primary: '#F48FB1',
      accent: '#CE93D8',
      background: '#1A1A2A',
      surface: '#252535',
      border: '#353545',
      error: '#EF5350',
      success: '#66BB6A',
      textPrimary: '#F0F0F5',
      textSecondary: '#A0A0B5',
      textTertiary: '#707085',
    },
    backgroundGradient: ['#F48FB11F', '#1A1A2A'],
    ...sharedTokens,
  },
  emberDark: {
    id: 'emberDark',
    name: 'Ember Dark',
    isDark: true,
    colors: {
      primary: '#FF8A65',
      accent: '#FFD54F',
      background: '#1A1A2A',
      surface: '#252535',
      border: '#353545',
      error: '#EF5350',
      success: '#66BB6A',
      textPrimary: '#F0F0F5',
      textSecondary: '#A0A0B5',
      textTertiary: '#707085',
    },
    backgroundGradient: ['#FF8A651F', '#1A1A2A'],
    ...sharedTokens,
  },
};

export const defaultTheme = themes.forest;
export default themes;
